- name: Disable default version of Redis
  ansible.builtin.shell:
    dnf module disable redis -y

- name: Enable version7 of Redis
  ansible.builtin.shell:
    dnf module enable redis:7 -y

- name: Install Redis
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: Update Redis Listen Address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Update Protected Mode
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode yes'
    replace: 'protected-mode no'

- name: Start Redis service
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: true




