- name: Import Java Common role
  ansible.builtin.include_role:
    name: common
    tasks_from: java

- name: Installing MySQL
  ansible.builtin.dnf:
   name:
    - mysql
    - python3-mysqlclient
   state: installed

#- name: Load {{ item }}
#  community.mysql.mysql_db:
#    state: import
#    name: all
#    target: /app/db/{{ item }}.sql
#    login_host: mysql-dev.pavanidevops.online
#    login_user: root
#    login_password: RoboShop@1
#    loop:
#      - schema
#      - app-user
#      - master-data

- name: Load {{ item }}
  ansible.builtin.shell: mysql -h mysql-{{ ENV }}.pavanidevops.online -uroot -pRoboShop@1 < /app/db/{{ item }}.sql
  loop:
    - schema
    - app-user
    - master-data

