- name: Installing MySQL
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Starting the MySQL service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Set MySQL Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1

