- name: Adding Application User
  ansible.builtin.user:
    name: roboshop

- name: Removing the application directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating the application directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading and extracting the App content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ app_name }}-v3.zip
    dest: /app
    remote_src: yes


